### ISSUE TITLE
Missing Core Field Type

### ISSUE THREAD

**Issue by fbray** [acquia/drupal-spec-tool#2]
The Field Types column on the hidden Settings sheet of your [Google Sheet](https://docs.google.com/spreadsheets/d/1G2LnWLVcZczxjp2SQt7XNjMvdNonmcgjx7RhFm2nhMw/edit?usp=sharing) is missing the core "Telephone number" field.  The corresponding form field widget, however, is available.

**Comment by TravisCarden** [comment]
Thanks, @fbray! The omission has been corrected. You can, of course, add the missing value to your own copy of the sheet.
