### ISSUE TITLE
Autogenerate machine names in spreadsheet

### ISSUE THREAD

**Issue by NickWilde1990** [acquia/drupal-spec-tool#21]
I don't like manually typing the machine name in most circumstances. Especially when creating a lot of content types it is boring.
So I've been using this formula: `=LEFT(LOWER(REGEXREPLACE(B#,"W", "_")),32)`
As far as I've been able to determine, there isn't a great method to place that automatically in new rows and still be able to enter a custom value if needed/desired. So I've been using an installed trigger on the google sheet document (onChange):
```
function onChange(e) {
  var sheet = e.source.getActiveSheet();
  if (e.changeType === "INSERT_ROW") {
    if (sheet == "Bundles" || sheet == "Menus" || sheet == "Views") {
      var range = sheet.getRange('C1:C');
      var values = range.getValues();
      range.setValues(values.map(function (row, index) {
        if (!row[0]) {
          i = index + 1;
          return ['=LEFT(LOWER(REGEXREPLACE(B' + i + ',"\W", "_")),32)'];
        }
        return row;
      }));
    }
  }
}
```
It does have some negatives and positives vs an onEdit trigger. onEdit is probably worse for performance, but can be smarter - set the value once even if you change the display name. The important thing though, is onEdit, doesn't need to be manually enabled for each user like onChange does as far as I can determine. 

Given that, if I get around to polishing the onEdit version of that for myself, would you be interested in it?
(Envisioned Features: 
- autogenerate the machine name
- don't change an existing machine name even if prior name was autogenerated)

**Comment by TravisCarden** [comment]
Hi, @NickWilde1990. I love the idea! As long as it doesn't noticeably damage performance, I would absolutely be interested in it. An additional "nice to have" feature would be to regenerate the value if you delete the machine name and unfocus the cell. Thanks so much. I look forward to seeing what you come up with!

**Comment by NickWilde1990** [comment]
Hey @TravisCarden,
Continued playing and I don't notice any slow down with my latest. That said, Google drive is always slow on my system (don't have the fastest system and usually have a lot of stuff open).  Haven't done regenerative a deleted machine name, but very easy. I figure start with this and have someone else (or a few) test performance. Autoprefixes fields with field_. I did confirm that it works in the new document if you duplicate the document.

For ease of testing, I've set a sheet as public with link: https://docs.google.com/spreadsheets/d/1-0odmCKqKgcxgMmDe5KfNKsie5uOXy8lgZqx7XYWPQg/edit?usp=sharing
Edit as desired for testing, its a duplicate.

Here's the code I've used:
<code>
function onEdit (e) {
	var sheet = e.source.getActiveSheet(),
		range = e.range;
	switch(sheet.getName()) {
		case 'Bundles':
		case 'Menus':
		case 'Views':
		case 'Image styles':
		case 'Migrations':
		case 'Workflows':
		case 'User roles':
			if (e.range.getColumn() == 2) {
				setMachineName(e.range, 'C', sheet);
			}
			break;
		case 'Views displays':
		case 'Workflow states':
		case 'Workflow transitions':
			if (e.range.getColumn() === 3) {
				setMachineName(e.range, 'D', sheet);
			}
			break;
        case 'Fields':        
			if (e.range.getColumn() === 4) {
				setMachineName(e.range, 'E', sheet, 'field_');
			}
			break;
        default:
            return;
	}
}

function setMachineName(range, target, sheet, prefix) {
	var id = sheet.getRange(target + range.getRow()),
		label = prefix + range.getValue();
	if (!id.getValue() && label) {
		id.setValue(label.toLowerCase().replace(/\W/g, '_').substring(0,32));
	}
}
</code>

**Comment by TravisCarden** [comment]
Thanks, @NickWilde1990! I'll give this a look as soon as I can.

**Comment by TravisCarden** [comment]
All right, @NickWilde1990. I've done my testing and gone ahead and integrated it into [the upstream spreadsheet](https://docs.google.com/spreadsheets/d/1GDNEzJe_rWdM3oG_kbBEH8r11Pcy4a1xJ1oglVBsZRE/edit?usp=sharing). Thanks so much for your contribution! :smiley:
