### ISSUE TITLE
Create wiki

### ISSUE THREAD

**Issue by danepowell** [acquia/drupal-spec-tool#23]
The blog post announcing the spec tool is very well written but remains the primary/only form of documentation for the tool, and doesn't lend itself to collaboration. Long-term, I think we should have documentation that lives alongside the tool.

I have taken a first crack at creating a wiki in my personal fork of drupal-spec-tool: https://github.com/danepowell/drupal-spec-tool/wiki

Basically, I started by copying most of the text from the blog post verbatim and splitting it up into three general pages (overview/features/usage). I then made just a few small tweaks, and added a large section to the "usage" page with some lessons we've learned on projects in the field.

Let me know if you have any feedback. If it looks good, you can either pull it in here or give me push access and I'll take care of it. We might also want to tweak it and the README just a little to acknowledge the existence of one another.

**Comment by ba66e77** [comment]
I think this wiki looks great. It's clear, approachable, and covers not just the how but the why.

**Comment by danepowell** [comment]
@TravisCarden have you had a chance to review this? If you're short on time and want help copying it over, I'm happy to help if you give me push access.

**Comment by TravisCarden** [comment]
Hello, @danepowell. I provided some feedback to @ChuChuNaKu in a Google Sheet he shared with me. I've added you to the document and a related email thread. I'll reach out to you privately about getting push access to the repo.

**Comment by ChuChuNaKu** [comment]
@danepowell @TravisCarden  Sorry about that. I had it on my todo to address the feedback in the shared document. I can help out completing these changes this week.

**Comment by danepowell** [comment]
The wiki is now live!
https://github.com/acquia/drupal-spec-tool/wiki

@ChuChuNaKu @TravisCarden please review and let me know if I missed anything.

**Comment by TravisCarden** [comment]
Thanks, @danepowell and @ChuChuNaKu! 😃

**Comment by ChuChuNaKu** [comment]
Woot!
