### ISSUE TITLE
Small Google Sheet Edits

### ISSUE THREAD

**Issue by brayfe** [acquia/drupal-spec-tool#29]
While using this for a recent project, I found two small changes needed to the Google sheet template.

1. On the Settings tab, cell B28 should be "Number (float)" vs "Number (decimal)" which is repeated a second time, to ensure consistency with the Drupal Add Field dropdown.
1. On the Overview tab, hidden cell B3 should read "Custom Block type" to calculate the bundles correctly.

**Comment by TravisCarden** [comment]
Quite right! Both issues have been fixed in the current and upstream documents. I'll close this issue with a credit commit to the repo to represent your contribution. Thanks, @brayfe! 😃
