### ISSUE TITLE
Whitespace causing field comparison issue

### ISSUE THREAD

**Issue by AccessPhil** [acquia/drupal-spec-tool#3]
Hi!
I'm liking this tool so far, just had a little problem that I managed to fix.

# Problem
In a new project I was working on I couldn't get the tests for "Then exactly the following fields should exist" to pass. The problem manifested itself in Behat telling me that a field was both present and missing from the specification. Here is the output I was receiving.

      TravisCarden\BehatTableComparison\UnequalTablesException: --- Missing fields (present in specification, absent from Drupal)
      | Paragraph type | Section Component | Title Icon | field_para_icon       | List (text)  |  | 1 | Select list |  | Select the icon you wish to appear alongside the component title                                                               
                                                                                        |
      +++ Unexpected fields (present in Drupal, absent from specification)
      | Paragraph type | Section Component | Title Icon | field_para_icon       | List (text)  |  | 1 | Select list |  | Select the icon you wish to appear alongside the component title                                                                                                                                                  |

I found this a little odd. I eventually tracked this down to the way in which the fields are extracted from the feature file. For some reason an extra space was being added to the description of the field. This was happening even if I removed all of the spaces from the feature file.

      | Paragraph type | Section Component | Title Icon | field_para_icon       | List (text)  |  | 1 | Select list |  | Select the icon you wish to appear alongside the component title|

# Solution
The solution I found was to trim the description string as it is added to the list of fields. Line 150 of the ContentModelContext class.

            trim($field_config->getDescription()),

This allowed the specification of the field and the actual fields to match and so complete the test.

**Comment by TravisCarden** [comment]
Thanks for the report, @AccessPhil. I'm glad you're liking the tool. 😃 l'm reluctant to modify any values taken from the field config. I'm not sure that's actually where your problem is. Does the field description have that whitespace in the database? Looking at the output you received, I would expect to find 63 spaces, a newline character, and 82 more spaces. Your specification contains 146 spaces and no newlines. Note that there's presently no way to encode newlines in a Gherkin table (that I'm aware of). In the case of field descriptions, since newlines won't display in the Drupal UI anyway, I would suggest simply removing them from the configuration. Please let me know if I've correctly diagnosed your issue.

**Comment by AccessPhil** [comment]
Hi Travis,
I did originally start writing out my investigations. However, that lead me to the inevitable conclusion that the config we had for that field contained some whitespace at the end.

Here is the offending line in our config for the field above.
```
description: 'Select the icon you wish to appear alongside the component title '
```

Correcting that sorted out the problem. I guess a fresh pair of eyes was all that was needed to figure our what was really going on.
Sorry to have wasted your time :)
Phil

**Comment by TravisCarden** [comment]
Glad you figured it out, @AccessPhil. Please don't consider it a waste of my time. I'm happy I could help. :)
