### ISSUE TITLE
mink-zombie-driver Dependency?

### ISSUE THREAD

**Issue by greggmarshall** [acquia/drupal-spec-tool#33]
The mink-zombie-driver dependency in Drupal Spec Tool is causing an issue when I try to install the tool via composer inside a Lando environment (which is supported by ADS).  The Lando PHP doesn't have the sockets extension included and I haven't figured out how to install/enable it (no answer on the Lando issue queue yet either).

Is there a reason for the mink-zombie-driver dependency that isn't satisfied by the mink-goutte-driver, mink-selenium2-driver or chrome-mink-driver that come when Behat is installed via composer?

**Comment by TravisCarden** [comment]
Hello, @greggmarshall. The Drupal Spec Tool doesn't have a direct dependency on `mink-zombie-driver`, nor does a fully built-out dependency graph on a vanilla build contain one:

```
$ composer why behat/mink-zombie-driver


  [InvalidArgumentException]
  Could not find package "behat/mink-zombie-driver" in your project


depends [-r|--recursive] [-t|--tree] [--] <package> [<constraint>]

```

You can use the above command to find out what's causing your build to require it.

**Comment by greggmarshall** [comment]
Very odd, when I removed Drupal Spec Tool from the composer.json and rebuilt the error went away, so I assumed it was a dependency of a dependency, but now when I added it back via composer require I didn't get the error.  I guess I didn't hold my mouth right the first time.

Thanks for the composer why command, I've got a new tool in my box.
