### ISSUE TITLE
Add Layout Builder Field Type

### ISSUE THREAD

**Issue by mikemadison13** [acquia/drupal-spec-tool#34]
Currently we have panelizer as a field type and that is the default for basic pages / landing pages. However, with newer versions of Drupal core and Lightning, we need Layout Builder as a field type instead of just panelizer.

It looks like adding this to the settings tab (good call @TravisCarden ) works fine.

**Comment by TravisCarden** [comment]
Thanks, @mikemadison13. I've added a "Layout Section" field type and a "Layout Builder Widget" form field widget to the current and upstream spreadsheets.
