### ISSUE TITLE
Add Acquia Site Studio Support to Spec Tool

### ISSUE THREAD

**Issue by mikemadison13** [acquia/drupal-spec-tool#47]
Sites that utilize Site Studio have slightly different definitions required for custom Helpers, Components, etc. It would be great if the spec tool supported these options (perhaps under other tabs than the current bundle / field definitions) so that projects using Site Studio / Cohesion can also use the Spec Tool to define these features.

**Comment by TravisCarden** [comment]
Sounds reasonable, @mikemadison13. Can you you provide concrete details? Maybe a rough example in a Google Sheet?

**Comment by mikemadison13** [comment]
yeah, i'm working with @pavlosdan and @aellison to try and come up with some more concrete recommendations! just wanted to get this out there because I have been forgetting to do so for a week or more.

**Comment by aellison** [comment]
Created an OKR to work on recommendations this quarter.
https://app.betterworks.com/app/#/goal/10100331

**Comment by FelipeJust** [comment]
Hi everyone, there are some news about this? I think it's a great idea to help the community

**Comment by TravisCarden** [comment]
Ooh! Sorry I never updated this issue... 😬  I switched to using Acquia CMS: Community Starter Kit in https://github.com/acquia/drupal-spec-tool/releases/tag/v6.0.0.
