### ISSUE TITLE
Automatic Import of Existing Drupal Site Architecture into Drupal Spec Tool

### ISSUE THREAD

**Issue by greggmarshall** [acquia/drupal-spec-tool#48]
Just as #46 would automatically generate the configuration files for a Drupal Spec Tool spreadsheet, it would be really useful for teams taking over maintenance and/or extension of an existing site to be able to import that site's configuration into DST without having to enter the information manually.

**Comment by TravisCarden** [comment]
It sure would, @greggmarshall! In fact, there's already an issue for it: #27. Closing this one as a duplicate.

**Comment by greggmarshall** [comment]
Sorry, didn't notice that issue.
