### ISSUE TITLE
Add Image Style, Queue, and Display Mode mappings

### ISSUE THREAD

**Issue by agentrickard** [acquia/drupal-spec-tool#5]
I was comparing this tool to our older Palantir build spec. There are a few items there that I'd like to add here:

* Image styles, which are fairly critical to all builds
* Display modes and field settings for bundles
* Queues (entity, node) as needed

Our original is at https://docs.google.com/spreadsheets/d/15htLLWLguhwiuTLg_nndQNpgWVdUMy6UaR_d1q-v6iw/edit?usp=sharing. 

What's the best way to contribute these items?

**Comment by TravisCarden** [comment]
Hi, @agentrickard. I'd love to see some of those added to the tool. I think the best way to contribute them would be to provide a document with sheets (tabs) I can either copy out or recreate. My first requirement for all data is that it be denormalized. So "Image styles", for example, would need to become two sheets: "Image styles" and "Image style effects", similar to "Views" and "Views displays". If you have or want to write Behat step definitions, that would be great, but I don't require it. Neither would I expect you to wire up the Gherkin generation, which is currently a rather tedious, manual process. Thanks for helping out!

**Comment by TravisCarden** [comment]
@agentrickard, I've added image styles to [my upstream document](https://docs.google.com/spreadsheets/d/1GDNEzJe_rWdM3oG_kbBEH8r11Pcy4a1xJ1oglVBsZRE/edit?usp=sharing) for future release. Please take a look and share any feedback you have. If you'd like to try the corresponding Behat step definitions, check out the `develop` branch.

**Comment by agentrickard** [comment]
I can't test the Behat stuff, but the sheet looks great.
