### ISSUE TITLE
Add a Drupal 9 Google Sheet based on Acquia CMS

### ISSUE THREAD

**Issue by greggmarshall** [acquia/drupal-spec-tool#58]
The current Drupal 9 Google Sheet has data based on the Acquia Lightning profile, which is end of life. 

Since Lightning has been more/less replaced by Acquia CMS, it would be very useful to Acquia CMS users to have the Google Sheet default to entities, fields, workflows, etc defined by Acquia CMS.  That would make it easier to integrate Drupal Spec Tool into projects using Acquia CMS as their starting point.

**Comment by TravisCarden** [comment]
Quite so, @greggmarshall! Thank you. We'll work on this as soon as we can. 👍

**Comment by TravisCarden** [comment]
Sorry for the long wait, @greggmarshall! The Google Sheet and the default feature files have been updated and released. Enjoy. 🙂

**Comment by greggmarshall** [comment]
Thanks, much appreciated.
