### ISSUE TITLE
Overview Formulas Missing in Google Sheet

### ISSUE THREAD

**Issue by fbray** [acquia/drupal-spec-tool#6]
Thanks again for all your work @TravisCarden!  I've discovered that the formula for the Views and Views Displays rows on the protected Overview sheet are missing.  I've corrected my local values, but thought it might be helpful to update the source for others.  The values *should* be as below, if my understanding of the sheet is correct.

Thanks!

D11:   `=COUNTIF(Views!D2:D, "=x")`
E11:   `=COUNTIFS(Views!D2:D, "<>", Views!D2:D, "<>d")`
D12:  `=COUNTIF('Views displays'!E3:E, "=x")`
E12:  `=COUNTIFS('Views displays'!E2:E, "<>", 'Views displays'!E2:E, "<>d")`

**Comment by TravisCarden** [comment]
Ah, thank you, @fbray! The fix has been applied. I appreciate your contributions. :)
