### ISSUE TITLE
Type error trying to test media.feature

### ISSUE THREAD

**Issue by Peppe87** [acquia/drupal-spec-tool#60]
Hi,

I'm on a  9.3.x site, with php 8.1. 

If I try to test media.feature, I got the following error

>   Type error: Drupal\Core\Routing\UrlGenerator::setContext(): Argument #1 ($context) must be of type Symfony\Component\Routing\RequestContext, null given (Behat\Testwork\Call\Exception\FatalThrowableError)

While the _Image effects_ scenario is run.

**Comment by Peppe87** [comment]
Hi, thanks for the quick reply and  for the welcoming. 

I tried with a clean D9 install and that feature works, so it must be some patch\contrib module on my project that causes that bug :(  

I hope I'll have time in the nearby future to try to determine which is, in case I'll update you.

**Comment by TravisCarden** [comment]
You're welcome. I hope you figure it out!
