### ISSUE TITLE
Compatibility question.

### ISSUE THREAD

**Issue by mohammadzo** [acquia/drupal-spec-tool#66]
Hi team,

I have a Drupal 8.9 site with BLT 11.x and acquia/drupal-spec-tool 2.x and I have plan to update the site to BLT 12 and Drupal 9. 
To update the acquia/drupal-spec-tool what version I should update ? latest ?

Thank you,

**Comment by TravisCarden** [comment]
Hi, @mohammadzo. The 4.x branch, but Composer will handle that question for you when you update Drupal. For example:

```shell
composer require drupal/core-recommended:^9 --with-all-dependencies
```
