### ISSUE TITLE
Google sheet Fields -> Form Widget column -> Text field and Textfield

### ISSUE THREAD

**Issue by monaw** [acquia/drupal-spec-tool#67]
Currently the Google sheet Fields tab's Form Widget column has both "Text field" and "Textfield".  What's the difference or should one be removed?
![Screen Shot 2022-12-20 at 6 57 41 PM](https://user-images.githubusercontent.com/18472048/208810480-be48bd06-82e8-4aab-962c-289ff5185f8f.png)

**Comment by TravisCarden** [comment]
Hi, @monaw. Digging into this a little, I see the spreadsheet needs some updates for upstream changes to contrib modules. I'm in the process of making them. I'll keep you posted.

**Comment by TravisCarden** [comment]
Hey, @monaw. I made a few incremental fixes over time since last commenting here. I've finally had a chance to make a comprehensive update and release https://github.com/acquia/drupal-spec-tool/releases/tag/v6.0.0. I'm closing this issue as fixed. Let me know if you find any other problems. Thanks.
