### ISSUE TITLE
Custom entity for Bundle?

### ISSUE THREAD

**Issue by monaw** [acquia/drupal-spec-tool#70]
In the Google Sheet for the Bundles page, in the Type column, I entered "Custom entity" and got a validation error.  Is it not possible to add additional types?
![Screen Shot 2023-01-18 at 4 45 22 PM](https://user-images.githubusercontent.com/18472048/213329406-c8b2959f-357c-47c0-8184-65f78068838f.png)

I went into the "Data validation rules" dialog but don't see a way to add a new entry; I did some searching but didn't find an answer...your help is appreciated...
![Screen Shot 2023-01-18 at 4 53 16 PM](https://user-images.githubusercontent.com/18472048/213330262-61c81df9-f818-4d75-bded-eab43e51c8ca.png)

**Comment by TravisCarden** [comment]
Oh dear; I'm sorry, @monaw! Somehow I never saw this. 😬 The available content entity types are defined in the "Settings" tab, column C:

![Content entity types](https://github.com/acquia/drupal-spec-tool/assets/959246/60f97233-2c7a-4db9-a1a5-57693069e0de)

Adding a cell to the column for your custom type is all you need to do.

I'm closing this issue. Feel free to re-open it if the above doesn't solve the issue for you.
