### ISSUE TITLE
Request to update the module dependency for Drupal 10 latest versions

### ISSUE THREAD

**Issue by sairamraavi** [acquia/drupal-spec-tool#74]
Hi while upgrading to the Drupal 10 version I am facing the dependency issue related to this module 

 Problem 1
    - Root composer.json requires acquia/drupal-spec-tool ^4.1 -> satisfiable by acquia/drupal-spec-tool[4.1.0, 4.1.1].
    - acquia/drupal-spec-tool[4.1.0, ..., 4.1.1] require drupal/core ^9.0 -> found drupal/core[9.0.0-alpha1, ..., 9.5.x-dev] but it conflicts with your root composer.json require (^10.0).

**Comment by TravisCarden** [comment]
Hi, @sairamraavi. The Drupal Spec Tool `v4` doesn't support Drupal 10. Only `v6` does. Are you able to update?

**Comment by sairamraavi** [comment]
but i can see only v5 available. Can you please provide me any link if v6 is available

**Comment by TravisCarden** [comment]
@sairamraavi, I just did a comprehensive update and released (a stable) [`v6.0.0`](https://github.com/acquia/drupal-spec-tool/releases/tag/v6.0.0). I'm closing this on the assumption that that will do it for you. Feel free to re-open if not.
