### ISSUE TITLE
A dependency no longer exists

### ISSUE THREAD

**Issue by aamouri** [acquia/drupal-spec-tool#76]
Hello,

I got an error message when doing a composer install.
Version dev-master for "drupal/drupal-extension" no longer exists.

![image](https://github.com/acquia/drupal-spec-tool/assets/4353496/225b9ace-b940-4ab6-b445-ba2c7fae29a4)

Thank you for your help.

**Comment by jorgemd-cit** [comment]
Hello, I'm facing the same problem, the branch alias "dev-master" for "drupal/drupal-extension" was removed (https://github.com/jhedstrom/drupalextension/commit/d77136a6068ec286b9bd57c5cba400b82452859f)

I would suggest to update the dependency version to the actual version: "5.0.x-dev"

Thanks

**Comment by rodriguesdaniel** [comment]
Hello.
Facing the same issue here. Thanks for your support guys.

**Comment by danielarendwtt** [comment]
Same issue here.

**Comment by danielarendwtt** [comment]
https://github.com/acquia/drupal-spec-tool/pull/77

**Comment by aamouri** [comment]
Hello,

As a workaround, you can use my fork https://github.com/aamouri/drupal-spec-tool

    "require-dev": {
        "acquia/coding-standards": "^2.0",
        **"aamouri/drupal-spec-tool": "^6.0",**


    "repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        **"aamouri": {
            "type": "vcs",
            "url": "https://github.com/aamouri/drupal-spec-tool.git"
        }**
    },

**Comment by TravisCarden** [comment]
Thanks, everyone! I merged the fix in #77 and cut a new https://github.com/acquia/drupal-spec-tool/releases/tag/v6.1.0. (I snuck in PHP 8.2 support, too.) Enjoy! 🙂
